### ISSUE TITLE
Spinning beachball on Sketch 47.1 / High Sierra

### ISSUE THREAD

**Issue by songcarver** [joshdjuric/Skatter#4]
Not sure what's causing the issue, but on Sketch 47.1 / High Sierra I always get a spinning beachball after the last dialogue in the plugin flow. 
Plugin used to work fine for me earlier (thanks for making it!)

**Comment by joshdjuric** [comment]
Hi @songcarver - has it improved with Sketch 48? I've only got Sierra so I can't replicate. There's a chance you might have a complex shape or two that might be creating an issue; depending on the number of elements you're trying to skatter.

**Comment by songcarver** [comment]
Seems to be working again for me now on Sketch 48.2 / High Sierra. Thanks!
